baseURL = 'https://mati.arocena.dev/'
title = 'MATI.AROCENA.DEV'
paginate = 10

defaultContentLanguage = 'es'
defaultContentLanguageInSubdir = false

[params.author]
  email = "mati@arocena.dev"
  name = "Matias Arocena"

[outputs]
  home = ['html', 'rss']

[languages]
  [languages.es]
    languageName = 'Español'
    weight = 10
    contentDir = 'content/es'
    title = 'MATI.AROCENA.DEV'
    languageCode = 'es-UY'
    [languages.es.params]
      description = 'Blog personal de Matias Arocena'
  [languages.en]
    languageName = 'English'
    weight = 20
    contentDir = 'content/en'
    title = 'MATI.AROCENA.DEV'
    languageCode = 'en-US'
    [languages.en.params]
      description = 'Personal blog of Matias Arocena'


[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
